<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.9.2 on darwin)" generated="20210320 19:55:46.894" rpa="false">
<suite id="s1" name="contactPageTestSuite" source="/Users/deebasanober/eclipse-workspace/PlanIt-Assessment/robotframework/jupiterToysAutomation/contactPageTestSuite.robot">
<test id="s1-t1" name="Test_Case_01">
<kw name="Set Environment Path" library="CommonLib" type="setup">
<kw name="Run Keyword If" library="BuiltIn">
<doc>Runs the given keyword with the given arguments, if ``condition`` is true.</doc>
<arguments>
<arg>"${Browser}"=="Chrome"</arg>
<arg>Append To Environment Variable</arg>
<arg>PATH</arg>
<arg>/Users/deebasanober/eclipse-workspace/PlanIt-Assessment/robotframework/jupiterToysAutomation/Resources/../Driver</arg>
<arg>ELSE IF</arg>
<arg>"${Browser}"=="Safari"</arg>
<arg>Log</arg>
<arg>Starting Safari Driver</arg>
</arguments>
<kw name="Log" library="BuiltIn">
<doc>Logs the given message with the given level.</doc>
<arguments>
<arg>Starting Safari Driver</arg>
</arguments>
<msg timestamp="20210320 19:55:47.222" level="INFO">Starting Safari Driver</msg>
<status status="PASS" starttime="20210320 19:55:47.222" endtime="20210320 19:55:47.222"></status>
</kw>
<status status="PASS" starttime="20210320 19:55:47.221" endtime="20210320 19:55:47.222"></status>
</kw>
<kw name="Set Selenium Speed" library="SeleniumLibrary">
<doc>Sets the delay that is waited after each Selenium command.</doc>
<arguments>
<arg>2000s</arg>
</arguments>
<status status="PASS" starttime="20210320 19:55:47.222" endtime="20210320 19:55:47.223"></status>
</kw>
<status status="PASS" starttime="20210320 19:55:47.221" endtime="20210320 19:55:47.223"></status>
</kw>
<kw name="Open Browser To Page" library="CommonLib">
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the optional ``url``.</doc>
<arguments>
<arg>${url}</arg>
<arg>browser=${Browser}</arg>
</arguments>
<msg timestamp="20210320 19:55:47.224" level="INFO">Opening browser 'Safari' to base url 'http://jupiter.cloud.planittesting.com'.</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<status status="FAIL" starttime="20210320 19:57:45.597" endtime="20210320 19:57:45.598"></status>
</kw>
<msg timestamp="20210320 19:57:45.598" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
<status status="FAIL" starttime="20210320 19:55:47.223" endtime="20210320 19:57:45.598"></status>
</kw>
<status status="FAIL" starttime="20210320 19:55:47.223" endtime="20210320 19:57:45.599"></status>
</kw>
<kw name="Test Closure" library="CommonLib" type="teardown">
<kw name="Run Keyword If Test Failed" library="BuiltIn">
<doc>Runs the given keyword with the given arguments, if the test failed.</doc>
<arguments>
<arg>Take Screenshot for Failure</arg>
</arguments>
<kw name="Take Screenshot for Failure" library="CommonLib">
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<arguments>
<arg>${TEST NAME}_FailedScreenshot</arg>
</arguments>
<msg timestamp="20210320 19:57:45.608" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af07fa0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.609" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af53ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.610" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af53c70&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20210320 19:57:45.613" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af33910&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.614" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10afbf5b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.615" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10afbf760&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.630" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10afbf8e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20210320 19:57:45.611" endtime="20210320 19:57:45.630"></status>
</kw>
<msg timestamp="20210320 19:57:45.630" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10afbf8e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20210320 19:57:45.630" level="INFO">/usr/local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py:1030: UserWarning: name used for saved screenshot does not match file type. It should end with a `.png` extension
  warnings.warn("name used for saved screenshot does not match file "</msg>
<msg timestamp="20210320 19:57:45.632" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af53df0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20210320 19:57:45.603" endtime="20210320 19:57:45.632"></status>
</kw>
<status status="FAIL" starttime="20210320 19:57:45.602" endtime="20210320 19:57:45.632"></status>
</kw>
<status status="FAIL" starttime="20210320 19:57:45.601" endtime="20210320 19:57:45.632"></status>
</kw>
<kw name="Close Browser" library="SeleniumLibrary">
<doc>Closes the current browser.</doc>
<msg timestamp="20210320 19:57:45.634" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041070&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2</msg>
<msg timestamp="20210320 19:57:45.634" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041190&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2</msg>
<msg timestamp="20210320 19:57:45.635" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b0412e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2</msg>
<msg timestamp="20210320 19:57:45.644" level="ERROR">When closing browser, received exception: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041430&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<kw name="Capture Page Screenshot" library="SeleniumLibrary">
<doc>Takes a screenshot of the current page and embeds it into a log file.</doc>
<msg timestamp="20210320 19:57:45.644" level="INFO">Cannot capture screenshot because no browser is open.</msg>
<status status="PASS" starttime="20210320 19:57:45.644" endtime="20210320 19:57:45.645"></status>
</kw>
<msg timestamp="20210320 19:57:45.648" level="FAIL">MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041430&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<status status="FAIL" starttime="20210320 19:57:45.632" endtime="20210320 19:57:45.648"></status>
</kw>
<status status="FAIL" starttime="20210320 19:57:45.600" endtime="20210320 19:57:45.649">Several failures occurred:

1) MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af53df0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

2) MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041430&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</kw>
<doc>Test Case to Validate the Contacts Page Mandatory Fields</doc>
<tags>
<tag>smoke-p2</tag>
</tags>
<status status="FAIL" starttime="20210320 19:55:47.220" endtime="20210320 19:57:45.649" critical="yes">Execution terminated by signal

Also teardown failed:
Several failures occurred:

1) MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af53df0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))

2) MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041430&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</status>
</test>
<doc>Test Cases related to Contact Page</doc>
<status status="FAIL" starttime="20210320 19:55:46.895" endtime="20210320 19:57:45.650"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1">smoke-p2</stat>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="contactPageTestSuite">contactPageTestSuite</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210320 19:57:45.598" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: Execution terminated by signal</msg>
<msg timestamp="20210320 19:57:45.608" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af07fa0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.609" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af53ac0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.610" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af53c70&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.613" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10af33910&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.614" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10afbf5b0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.615" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10afbf760&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot</msg>
<msg timestamp="20210320 19:57:45.630" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2/screenshot (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10afbf8e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
<msg timestamp="20210320 19:57:45.634" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041070&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2</msg>
<msg timestamp="20210320 19:57:45.634" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041190&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2</msg>
<msg timestamp="20210320 19:57:45.635" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b0412e0&gt;: Failed to establish a new connection: [Errno 61] Connection refused')': /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2</msg>
<msg timestamp="20210320 19:57:45.644" level="ERROR">When closing browser, received exception: HTTPConnectionPool(host='127.0.0.1', port=49652): Max retries exceeded with url: /session/46A98D7C-6C60-4FE7-8369-EBD4CFFB4BA2 (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x10b041430&gt;: Failed to establish a new connection: [Errno 61] Connection refused'))</msg>
</errors>
</robot>
